Fixed so that is checks for updates instead of updating automatically

diff --git a/mktex b/mktex
--- a/mktex
+++ b/mktex
@@ -1,4 +1,7 @@
 #!/bin/bash
+######### commit id ############
+73a573554f8e483f571090dd9c3bc3868e2c9768
+################################
 clear
 ###################################################################################
 # Source: https://github.com/tmlarsson/mktex
@@ -133,17 +136,34 @@ fi
 # since you should NEVER run some random code of the internet 
 # which requires the sudo command without trusting it. NEVER!
 if [ ! -z $update ]; then
+    echo -n "Checking for updates..."
+    if ! wget -O /tmp/mktex.html https://github.com/tmlarsson/mktex 2>/dev/null; then
+        echo "[Failed]"
+    exit 0
+    else
+        echo "[OK]"
+    fi
+    id=$(cat /tmp/mktex.html |grep -oE -m 1 "mktex\/commit\/.{0,40}"|cut -c 14-)
+    idNow=$(head -n 3 /usr/local/bin/mktex | tail -n -1)+
+    if [ "$id" == "$idNow" ]; then
+        echo "No update available..."
+        exit 0
+    else
+        echo "Update available!"
+    fi
+    
     # Checks if update is run as root. 
     # Otherwise it terminates the script
     echo -n "Install local or globally? [l/g]: "
     read installPath
-
     if [ $installPath == "l" ]; then
         dir=$PWD
         cd /tmp
         if git clone https://github.com/tmlarsson/mktex &>/dev/null
         then
-            cd mktex; mv mktex "$dir"; cd ..
+            cd mktex; 
+            sed -e "s/"$id"/"$idNow"/" ./mktex > ./mktex-tmp
+            mv mktex-tmp "$dir"; cd ..
             rm -rf mktex; cd "$dir"
             chmod +x mktex
             exit 0
@@ -159,15 +179,17 @@ if [ ! -z $update ]; then
             echo [OK]
             cd mktex
             if sudo mv mktex /usr/local/bin; then
-                echo "Succeded in installing the update!"
-                sudo chmod +x /usr/local/bin/mktex
                 echo $(date +%s) > /tmp/mktex-update
-            else
-            echo "Failed to install update..."
+                sed -e "s/"$id"/"$idNow"/" /usr/local/bin/mktex > /tmp/mktex-script
+                sudo mv /tmp/mktex-script /usr/local/bin/mktex
+                sudo chmod +x /usr/local/bin/mktex
+                echo "Succeded in installing the update!"
+            fi
+        else
+                echo "Failed to install update..."
         fi
         cd ../ && rm -rf mktex
         exit 0
-    fi
     else
         echo "ERROR: \""$installPath"\" is not a valid input."
         exit 0
