Updated code

diff --git a/mktex b/mktex
--- a/mktex
+++ b/mktex
@@ -11,28 +11,13 @@ UPDATE=
 MINTED= # -shell-escape only needs to be used when minted is used due to potentially security flaw.
 VERBOSE='grep -iE "^.*:[0-9]*:.*\|warning\| error .*$"'
 
-# Initial setup
-if [ ! -d ~/.mktex ]; then
-    echo "Building initial setup..."
-    echo ""
-    if ! git clone ssh://github.com/tmlarsson/mktex ~/.mktex; then
-        echo "Failed to get mktex..."
-        exit 0
-    else
-        echo ""
-        echo "To continue, you need to add ~/.mktex to your"
-        echo "path or add a symlink to /usr/local/bin or similar."
-    fi
-    
-fi
-
 # Check for input
 if [ "$#" == 0 ]; then
     echo "No input..."
     exit 1
 fi
 
-while [[ $# > 0 ]]
+while [[ $# -gt 0 ]]
 do
 key="$1"
 case $key in
@@ -71,14 +56,14 @@ case $key in
     ;;
     *)
     TEMP="$1"
-    if [ ! -z "$UPDATE"  ]; then
-        if [[ $TEMP =~ ".tex" ]]; then
+    if [ ! -z "$UPDATE" ] && [ ! -z "$VERSION" ]; then
+        if [[ $TEMP =~ .tex ]]; then
             TEMP=${TEMP%.tex}
         fi
-        if [[ "$TEMP" =~ "." ]]; then
+        if [[ "$TEMP" =~ . ]]; then
             TEMP=${TEMP%.}
         fi
-        if [[ ${TEMP:0:1} == "-" ]]; then
+        if [[ ${TEMP:0:1} == - ]]; then
             echo "ERROR: \"$TEMP\" is not a valid argument..."
             echo ""
             echo "Here is the help for you:"
@@ -89,7 +74,6 @@ case $key in
             exit 1  
         fi
     fi
-
     FILENAME="$TEMP"
     ;;
 esac
@@ -122,23 +106,15 @@ if [ "$HELP" == true ]; then
     exit 0
 fi
 
-# Updates mktex. This creates a script in the tmp folder
-# that will fetch the newest file from github.
-# This does however require the user to use the sudo 
-# command to move the new file to the /usr/local/bin folder.
-# However, since the program is open source you can always check
-# the source code to inspect my work. This should always be done
-# since you should NEVER run some random code of the internet 
-# which requires the sudo command without trusting it. NEVER!
+# Updates mktex.
 if [ ! -z $update ]; then
     # Install update
-    cd ~/.mktex
+    cd ~/.mktex ||exit
     if git pull --rebase --stat origin master; then
-        echo "Updated mktex to most recent update"
+        echo "Updated mktex to most recent update."
     else
         echo "Failed to get update..."
     fi
-
     exit 0
 fi
 
@@ -148,7 +124,7 @@ if [ ! -z $gettex ]; then
     dir=$PWD
     echo -n "Fetching the template..."
     
-    cd /tmp
+    cd /tmp ||exit 0
 
     if [ -d "latex-template" ]; then
         rm -rf latex-template
@@ -157,21 +133,21 @@ if [ ! -z $gettex ]; then
     if git clone https://github.com/tmlarsson/latex-template &>/dev/null
     then
         echo "[OK]"
-        cd latex-template
+        cd latex-template ||exit
         echo -n "Presentation or Report? [p/r]: "
-        read doc
-        if [ $doc == "p" ]; then
-            cd Presentation
-        elif [ $doc == "r" ]; then
-            cd Report
+        read -r doc
+        if [ "$doc" == "p" ]; then
+            cd Presentation ||exit
+        elif [ "$doc" == "r" ]; then
+            cd Report ||exit
         else
-            echo "ERROR: \""$doc"\" is not a valid input."
+            echo "ERROR: \" $doc \" is not a valid input."
             exit 0
         fi
 
-        if ! mv *.tex "$dir" ;
+        if ! mv ./*.tex "$dir" ;
         then
-            echo "ERROR: The directory "$dir" does not exist."
+            echo "ERROR: The directory $dir does not exist."
             exit 0
         fi
         cd ..
@@ -200,7 +176,7 @@ fi
 
 # Check if no filename is specified.
 # If no filename is given then exit the program
-if [ -z $FILENAME ]; then
+if [ -z "$FILENAME" ]; then
     echo "ERROR: No filename was specified."
     exit 0
 fi
@@ -212,7 +188,7 @@ fi
 if [ "$TIKZ" == true ]; then
     echo -n "Compiling TikZ picure using $compiler..."
 
-    tikzresult=$(max_print_line=2048 $compiler $MINTED -interaction=nonstopmode -file-line-error "${FILENAME%.tex}" 2>/tmp/tikzERR $VERBOSE)
+    tikzresult=$(max_print_line=2048 $compiler $MINTED -interaction=nonstopmode -file-line-error "${FILENAME%.tex}" 2>/tmp/tikzERR "$VERBOSE")
 
     if [ -z "$tikzresult" ]; then
         echo "[OK]"
@@ -262,14 +238,14 @@ if [ "$BIBER" == true ]; then
     while [ "$runAgain" == true ]; do
         echo -n "biber..."
         biber "$FILENAME" 1>/tmp/bibres 2>/tmp/biberr
-        bibRES=$(cat /tmp/bibres | grep -i "^.*:[0-9]*:.*\|warn\| error .*$")
+        bibRES=$(cat </tmp/bibres | grep -i "^.*:[0-9]*:.*\|warn\| error .*$")
         bibERR=$(</tmp/biberr)
         echo "[OK]"
 
         # Check fo data bug in biber
         vartest=$(echo "$bibERR" | grep "no data found")
         if [ ! -z "$vartest" ]; then
-            rm -rf `biber --cache`
+            rm -rf "$(biber --cache)"
             echo ""
             echo "Removed biber cache..."
             echo "Compiling again..."
@@ -285,12 +261,12 @@ echo -n "$compiler: Second sweep..."
 
 max_print_line=2048 $compiler $MINTED -interaction=nonstopmode -file-line-error "${FILENAME%.tex}" 1>/tmp/latex-output 2>/tmp/latexerr 
 
-result=$(cat /tmp/latex-output | grep -i "^.*:[0-9]*:.*\|warning\| error .*$")
+result=$(cat </tmp/latex-output | grep -i "^.*:[0-9]*:.*\|warning\| error .*$")
 
 temp=$(echo "$result" |grep -i "The following entry could not be found")
 
 if [ ! -z "$temp" ]; then
-    bibres=$(cat /tmp/latex-output |grep -i "(biblatex) ")
+    bibres=$(cat </tmp/latex-output |grep -i "(biblatex) ")
     result+="\n$bibres"
 fi
 
@@ -298,7 +274,7 @@ fi
 echo "[OK]"
 
 # Prints the result, if there is any errors to display.
-if [ -z "$result" -a -z "$bibRES" ]; then
+if [ -z "$result" ] && [ -z "$bibRES" ]; then
     echo ""
     echo 'Compiled without errors!'
 elif [ ! -z "$result" ]; then
@@ -331,56 +307,56 @@ fi
 
 # Remove unnessesary files.
 if [ "$CLEAN" == true ]; then
-    if [ -f "${FILENAME}.log" ]; then
-        rm ${FILENAME}.log
+    if [ -f "${FILENAME}".log ]; then
+        rm "${FILENAME}".log
     fi
-    if [ -f "${FILENAME}.lof" ]; then
-        rm ${FILENAME}.lof
+    if [ -f "${FILENAME}".lof ]; then
+        rm "${FILENAME}".lof
     fi
-    if [ -f "${FILENAME}.blg" ]; then
-        rm ${FILENAME}.blg
+    if [ -f "${FILENAME}".blg ]; then
+        rm "${FILENAME}".blg
     fi
-    if [ -f "${FILENAME}.toc" ]; then
-        rm ${FILENAME}.toc
+    if [ -f "${FILENAME}".toc ]; then
+        rm "${FILENAME}".toc
     fi
-    if [ -f "${FILENAME}.out" ]; then
-        rm ${FILENAME}.out
+    if [ -f "${FILENAME}".out ]; then
+        rm "${FILENAME}".out
     fi
 
-    if [ -f "${FILENAME}.bbl" ]; then
-        rm ${FILENAME}.bbl
+    if [ -f "${FILENAME}".bbl ]; then
+        rm "${FILENAME}".bbl
     fi
-    if [ -f "${FILENAME}.aux" ]; then
-        rm ${FILENAME}.aux
+    if [ -f "${FILENAME}".aux ]; then
+        rm "${FILENAME}".aux
     fi
-    if [ -f "${FILENAME}.bcf" ]; then
-        rm ${FILENAME}.bcf
+    if [ -f "${FILENAME}".bcf ]; then
+        rm "${FILENAME}".bcf
     fi
-    if [ -f "${FILENAME}.run.xml" ]; then
-        rm ${FILENAME}.run.xml
+    if [ -f "${FILENAME}".run.xml ]; then
+        rm "${FILENAME}".run.xml
     fi
-    if [ -f "${FILENAME}.tex.bak" ]; then
-        rm ${FILENAME}.tex.bak
+    if [ -f "${FILENAME}".tex.bak ]; then
+        rm "${FILENAME}".tex.bak
     fi
-    if [ -f "${FILENAME}.fls" ]; then
-        rm ${FILENAME}.fls
+    if [ -f "${FILENAME}".fls ]; then
+        rm "${FILENAME}".fls
     fi
-    if [ -f "${FILENAME}.fdb_latexmk" ]; then
-        rm ${FILENAME}.fdb_latexmk
+    if [ -f "${FILENAME}".fdb_latexmk ]; then
+        rm "${FILENAME}".fdb_latexmk
     fi
-    if [ -f "${FILENAME}.snm" ]; then
-        rm ${FILENAME}.snm
+    if [ -f "${FILENAME}".snm ]; then
+        rm "${FILENAME}".snm
     fi
-    if [ -f "${FILENAME}.nav" ]; then
-        rm ${FILENAME}.nav
+    if [ -f "${FILENAME}".nav ]; then
+        rm "${FILENAME}".nav
     fi
-    if [ -f "${FILENAME}.lot" ]; then
-        rm ${FILENAME}.lot
+    if [ -f "${FILENAME}".lot ]; then
+        rm "${FILENAME}".lot
     fi
 fi
 
 
-dontopen=$(cat /tmp/latex-output | grep -i "^.*:[0-9]*:.*\|fatal error .*$") 
+dontopen=$(cat </tmp/latex-output | grep -i "^.*:[0-9]*:.*\|fatal error .*$") 
 
 if [ ! -z "$dontopen" ]; then
     exit 0
